//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by THIN.RC
//
#define IDR_MAINFRAME                   2
#define IDR_THINTYPE                    3
#define IDD_ABOUTBOX                    100
#define ID_THIN_ALGO4                   32774
#define ID_THIN_START                   32775
#define ID_THIN_SCANLINE                32777
#define ID_VIEW_FIT                     32778
#define ID_THIN_ALGO1                   32779
#define ID_THIN_ALGO2                   32780
#define ID_THIN_ALGO3                   32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
